; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:arduino]
platform = atmelavr
board = megaatmega2560
framework = arduino
; build_flags =
;   -std=gnu++17
lib_deps =
    ArduinoSTL
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BNO055 @ ^1.5.0
build_src_filter= +<arduino.cpp> -<tests/**>

; ================================================
; [DEBUG] - environments for testing individual components
; ================================================
[env:BNOReadings]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps =
    ArduinoSTL
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BNO055 @ ^1.5.0
build_src_filter= -<*> +<tests/BNOReadings.cpp>

[env:I2CScan]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter= -<*> +<tests/I2CScan.cpp>

[env:individualMotors]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps =
    ArduinoSTL
build_src_filter= -<*> +<tests/individualMotors.cpp>

[env:motorsSquare]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps =
    ArduinoSTL
build_src_filter= -<*> +<tests/motorsSquare.cpp>

[env:PIDStickIntoOneDirection]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps =
    ArduinoSTL
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BNO055 @ ^1.5.0
build_src_filter= -<*> +<tests/PIDStickIntoOneDirection.cpp>

[env:getBallAngle]
monitor_speed = 115200
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps =
    ArduinoSTL
build_src_filter= -<*> +<tests/getBallAngle.cpp>

[env:PIDLookForBall]
monitor_speed = 115200
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps =
    ArduinoSTL
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BNO055 @ ^1.5.0
build_src_filter= -<*> +<tests/PIDLookForBall.cpp>

[env:MUXReadings]
monitor_speed = 115200
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps =
    ArduinoSTL
build_src_filter= -<*> +<tests/MUX_readings.cpp>

[env:MUX_test]
monitor_speed = 115200
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps =
    ArduinoSTL
    Wire
    adafruit/Adafruit Unified Sensor
build_src_filter= -<*> +<tests/MUX_test.cpp>

[env:PIDTestWithMUX]
monitor_speed = 115200
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps =
    ArduinoSTL
    Wire
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BNO055 @ ^1.5.0
build_src_filter= -<*> +<tests/PIDTestWithMUX.cpp>

[env:DemoPIDWithMUX]
monitor_speed = 115200
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps =
    ArduinoSTL
    Wire
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BNO055 @ ^1.5.0
build_src_filter= -<*> +<tests/DemoPhotoPID_Showcase.cpp>
